[package]
name = "cozyvim"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.45"
directories = "6.0.0"
eframe = "0.36.2"
include_dir = "0.7.4"
rust-i18n = "4.2.2"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
toml = "1.1.6"

[dev-dependencies]
egui_kittest = { version = "0.36.2", features = ["wgpu", "snapshot"] }
image = "0.25.10"
